name: CustomEnchant
main: fr.kyll01.customenchant.Main
api-version: 1.19
author: Kyll01
version: 1.2
commands:
  ce:
    permission: customenchantgui.*
  cegui:
    permission: customenchantgui.*
  celist:
    permission: customenchantgui.celist
  cegive:
    permission: customenchantgui.cegive